services:
  server:
    image: blog-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    environment:
      DB_URI_FILE: /run/secrets/db_uri
      TEST_DB_URI_FILE: /run/secrets/test_db_uri
      ACCESS_TOKEN_SECRET_FILE: /run/secrets/access_token_secret
    secrets:
      - db_uri
      - test_db_uri
      - access_token_secret
    container_name: blog-backend
  app:
    image: blog-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: blog-frontend
  cypress:
    image: cypress/included:9.2.0
    depends_on:
      - app
      - server
    environment:
      CYPRESS_baseUrl: http://app:3000
      NODE_ENV: test
    working_dir: /e2e
    volumes:
      - ./frontend:/e2e
    container_name: e2e-tests
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-prod
    depends_on:
      - app # wait for the frontend container to be started

secrets:
  access_token_secret:
    file: backend/secrets/access_token_secret.txt
  db_uri:
    file: backend/secrets/db_uri.txt
  test_db_uri:
    file: backend/secrets/test_db_uri.txt